# Generated by Django 4.0 on 2022-04-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gwrwh',
            new_name='guruh',
        ),
    ]
