# Generated by Django 4.0.4 on 2022-05-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_rename_gwrwh_student_guruh'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bitiruvchi',
            field=models.BooleanField(default=False),
        ),
    ]
