# Generated by Django 4.0.4 on 2022-05-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_student_bitiruvchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='muallif',
            name='kitoblar_soni',
            field=models.SmallIntegerField(default=1),
        ),
    ]
